module.exports = {
  SCIENCE_DATA: [
    {
      title: 'Biodegradation of synthetic polymers in soils: Tracking carbon into CO(2) and microbial biomass.',
      authors: ['Zumstein MT', 'Schintlmeister A', 'Nelson TF', 'Baumgartner R', 'Woebken D', 'Wagner M', 'Kohler HE', 'McNeill K', 'Sander M'],
      journal: 'Sci Adv. 2018 Jul 25',
      issue: '4(7)',
      pages: 'eaas9024',
      doi: '10.1126/sciadv.aas9024',
    },
    {
      title: 'Ammonia Monooxygenase-Mediated Cometabolic Biotransformation and Hydroxylamine-Mediated Abiotic Transformation of Micropollutants in an AOB/NOB Coculture.',
      authors: ['Yu Y', 'Han P', 'Zhou LJ', 'Li Z', 'Wagner M', 'Men Y'],
      journal: 'Environ Sci Technol. 2018 Aug 21',
      issue: '52(16)',
      pages: '9196-9205',
      doi: '10.1021/acs.est.8b02801',
    },
    {
      title: 'Characterization of the First "Candidatus Nitrotoga" Isolate Reveals Metabolic Versatility and Separate Evolution of Widespread Nitrite-Oxidizing Bacteria.',
      authors: ['Kitzinger K', 'Koch H', 'Lücker S', 'Sedlacek CJ', 'Herbold C', 'Schwarz J', 'Daebeler A', 'Mueller AJ', 'Lukumbuzya M', 'Romano S', 'Leisch N', 'Karst SM', 'Kirkegaard R', 'Albertsen M', 'Nielsen PH', 'Wagner M', 'Daims H'],
      journal: 'MBio. 2018 Jul 10',
      issue: '9(4). pii',
      pages: 'e01186-18',
      doi: '10.1128/mBio.01186-18',
    },
    {
      title: 'Long-distance electron transport in individual, living cable bacteria.',
      authors: ['Bjerg JT', 'Boschker HTS', 'Larsen S', 'Berry D', 'Schmid M', 'Millo D', 'Tataru P', 'Meysman FJR', 'Wagner M', 'Nielsen LP', 'Schramm A'],
      journal: 'Proc Natl Acad Sci U S A. 2018 May 29',
      issue: '115(22)',
      pages: '5786-5791',
      doi: '10.1073/pnas.1800367115',
    },
    {
      title: 'Nitrospira.',
      authors: ['Daims H', 'Wagner M'],
      journal: 'Trends Microbiol. 2018 May',
      issue: '26(5)',
      pages: '462-463',
      doi: '10.1016/j.tim.2018.02.001',
    },
    {
      title: 'Cultivation and Genomic Analysis of "Candidatus Nitrosocaldus islandicus", an Obligately Thermophilic, Ammonia-Oxidizing Thaumarchaeon from a Hot Spring Biofilm in Graendalur Valley, Iceland.',
      authors: ['Daebeler A', 'Herbold CW', 'Vierheilig J', 'Sedlacek CJ', 'Pjevac P', 'Albertsen M', 'Kirkegaard RH', 'de la Torre JR', 'Daims H', 'Wagner M'],
      journal: 'Front Microbiol. 2018 Feb 14',
      issue: '9',
      pages: '193',
      doi: '10.3389/fmicb.2018.00193',
    },
    {
      title: 'Draft Genome Sequence of Telmatospirillum siberiense 26-4b1, an Acidotolerant Peatland Alphaproteobacterium Potentially Involved in Sulfur Cycling.',
      authors: ['Hausmann B', 'Pjevac P', 'Schreck K', 'Herbold CW', 'Daims H', 'Wagner M', 'Loy A'],
      journal: 'Genome Announc. 2018 Jan 25',
      issue: '6(4). pii',
      pages: 'e01524-17',
      doi: '10.1128/genomeA.01524-17',
    },
    {
      title: 'Ammonia-oxidising archaea living at low pH: Insights from comparative genomics.',
      authors: ['Herbold CW', 'Lehtovirta-Morley LE', 'Jung MY', 'Jehmlich N', 'Hausmann B', 'Han P', 'Loy A', 'Pester M', 'Sayavedra-Soto LA', 'Rhee SK', 'Prosser JI', 'Nicol GW', 'Wagner M', 'Gubry-Rangin C'],
      journal: 'Environ Microbiol. 2017 Dec',
      issue: '19(12)',
      pages: '4939-4952',
      doi: '10.1111/1462-2920.13971',
    },
    {
      title: 'Abiotic Conversion of Extracellular NH(2)OH Contributes to N(2)O Emission during Ammonia Oxidation.',
      authors: ['Liu S', 'Han P', 'Hink L', 'Prosser JI', 'Wagner M', 'Brüggemann N'],
      journal: 'Environ Sci Technol. 2017 Nov 21',
      issue: '51(22)',
      pages: '13122-13132',
      doi: '10.1021/acs.est.7b02360',
    },
    {
      title: 'Kinetic analysis of a complete nitrifier reveals an oligotrophic lifestyle.',
      authors: ['Kits KD', 'Sedlacek CJ', 'Lebedeva EV', 'Han P', 'Bulaev A', 'Pjevac P', 'Daebeler A', 'Romano S', 'Albertsen M', 'Stein LY', 'Daims H', 'Wagner M'],
      journal: 'Nature. 2017 Sep 14',
      issue: '549(7671)',
      pages: '269-272',
      doi: '10.1038/nature23679',
    },
    {
      title: 'AmoA-Targeted Polymerase Chain Reaction Primers for the Specific Detection and Quantification of Comammox Nitrospira in the Environment.',
      authors: ['Pjevac P', 'Schauberger C', 'Poghosyan L', 'Herbold CW', 'van Kessel MAHJ', 'Daebeler A', 'Steinberger M', 'Jetten MSM', 'Lücker S', 'Wagner M', 'Daims H'],
      journal: 'Front Microbiol. 2017 Aug 4',
      issue: '8',
      pages: '1508',
      doi: '10.3389/fmicb.2017.01508',
    },
    {
      title: 'Crenothrix are major methane consumers in stratified lakes.',
      authors: ['Oswald K', 'Graf JS', 'Littmann S', 'Tienken D', 'Brand A', 'Wehrli B', 'Albertsen M', 'Daims H', 'Wagner M', 'Kuypers MM', 'Schubert CJ', 'Milucka J'],
      journal: 'ISME J. 2017 Sep',
      issue: '11(9)',
      pages: '2124-2140',
      doi: '10.1038/ismej.2017.77',
    },
    {
      title: 'Capturing the genetic makeup of the active microbiome in situ.',
      authors: ['Singer E', 'Wagner M', 'Woyke T'],
      journal: 'ISME J. 2017 Sep',
      issue: '11(9)',
      pages: '1949-1963',
      doi: '10.1038/ismej.2017.59',
    },
    {
      title: 'Giant viruses with an expanded complement of translation system components.',
      authors: ['Schulz F', 'Yutin N', 'Ivanova NN', 'Ortega DR', 'Lee TK', 'Vierheilig J', 'Daims H', 'Horn M', 'Wagner M', 'Jensen GJ', 'Kyrpides NC', 'Koonin EV', 'Woyke T'],
      journal: 'Science. 2017 Apr 7',
      issue: '356(6333)',
      pages: '82-85',
      doi: '10.1126/science.aal4657',
    },
    {
      title: 'Cultivation and characterization of Candidatus Nitrosocosmicus exaquare, an ammonia-oxidizing archaeon from a municipal wastewater treatment system.',
      authors: ['Sauder LA', 'Albertsen M', 'Engel K', 'Schwarz J', 'Nielsen PH', 'Wagner M', 'Neufeld JD'],
      journal: 'ISME J. 2017 May',
      issue: '11(5)',
      pages: '1142-1157',
      doi: '10.1038/ismej.2016.192',
    },
    {
      title: 'A New Perspective on Microbes Formerly Known as Nitrite-Oxidizing Bacteria.',
      authors: ['Daims H', 'Lücker S', 'Wagner M'],
      journal: 'Trends Microbiol. 2016 Sep',
      issue: '24(9)',
      pages: '699-712',
      doi: '10.1016/j.tim.2016.05.004',
    },
    {
      title: 'Single cell stable isotope probing in microbiology using Raman microspectroscopy.',
      authors: ['Wang Y', 'Huang WE', 'Cui L', 'Wagner M'],
      journal: 'Curr Opin Biotechnol. 2016 Oct',
      issue: '41',
      pages: '34-42',
      doi: '10.1016/j.copbio.2016.04.018',
    },
    {
      title: 'Biotransformation of Two Pharmaceuticals by the Ammonia-Oxidizing Archaeon Nitrososphaera gargensis.',
      authors: ['Men Y', 'Han P', 'Helbling DE', 'Jehmlich N', 'Herbold C', 'Gulde R', 'Onnis-Hayden A', 'Gu AZ', 'Johnson DR', 'Wagner M', 'Fenner K'],
      journal: 'Environ Sci Technol. 2016 May 3',
      issue: '50(9)',
      pages: '4682-92',
      doi: '10.1021/acs.est.5b06016',
    },
    {
      title: 'Back to the Future of Soil Metagenomics.',
      authors: ['Nesme J', 'Achouak W', 'Agathos SN', 'Bailey M', 'Baldrian P', 'Brunel D', 'Frostegård Å', 'Heulin T', 'Jansson JK', 'Jurkevitch E', 'Kruus KL', 'Kowalchuk GA', 'Lagares A', 'Lappin-Scott HM', 'Lemanceau P', 'Le Paslier D', 'Mandic-Mulec I', 'Murrell JC', 'Myrold DD', 'Nalin R', 'Nannipieri P', 'Neufeld JD', 'et al'],
      journal: 'Front Microbiol. 2016 Feb 10',
      issue: '7',
      pages: '73',
      doi: '10.3389/fmicb.2016.00073',
    },
    {
      title: 'Intestinal Microbiota Signatures Associated with Inflammation History in Mice Experiencing Recurring Colitis.',
      authors: ['Berry D', 'Kuzyk O', 'Rauch I', 'Heider S', 'Schwab C', 'Hainzl E', 'Decker T', 'Müller M', 'Strobl B', 'Schleper C', 'Urich T', 'Wagner M', 'Kenner L', 'Loy A'],
      journal: 'Front Microbiol. 2015 Dec 15',
      issue: '6',
      pages: '1408',
      doi: '10.3389/fmicb.2015.01408',
    },
    {
      title: 'Complete nitrification by Nitrospira bacteria.',
      authors: ['Daims H', 'Lebedeva EV', 'Pjevac P', 'Han P', 'Herbold C', 'Albertsen M', 'Jehmlich N', 'Palatinszky M', 'Vierheilig J', 'Bulaev A', 'Kirkegaard RH', 'von Bergen M', 'Rattei T', 'Bendinger B', 'Nielsen PH', 'Wagner M'],
      journal: 'Nature. 2015 Dec 24',
      issue: '528(7583)',
      pages: '504-9',
      doi: '10.1038/nature16461',
    },
    {
      title: 'Advancements in the application of NanoSIMS and Raman microspectroscopy to investigate the activity of microbial cells in soils.',
      authors: ['Eichorst SA', 'Strasser F', 'Woyke T', 'Schintlmeister A', 'Wagner M', 'Woebken D'],
      journal: 'FEMS Microbiol Ecol. 2015 Oct',
      issue: '91(10). pii',
      pages: 'fiv106',
      doi: '10.1093/femsec/fiv106',
    },
    {
      title: 'Expanded metabolic versatility of ubiquitous nitrite-oxidizing bacteria from the genus Nitrospira.',
      authors: ['Koch H', 'Lücker S', 'Albertsen M', 'Kitzinger K', 'Herbold C', 'Spieck E', 'Nielsen PH', 'Wagner M', 'Daims H'],
      journal: 'Proc Natl Acad Sci U S A. 2015 Sep 8',
      issue: '112(36)',
      pages: '11371-6',
      doi: '10.1073/pnas.1506533112',
    },
    {
      title: 'Cyanate as an energy source for nitrifiers.',
      authors: ['Palatinszky M', 'Herbold C', 'Jehmlich N', 'Pogoda M', 'Han P', 'von Bergen M', 'Lagkouvardos I', 'Karst SM', 'Galushko A', 'Koch H', 'Berry D', 'Daims H', 'Wagner M'],
      journal: 'Nature. 2015 Aug 6',
      issue: '524(7563)',
      pages: '105-8',
      doi: '10.1038/nature14856',
    },
    {
      title: 'Ecophysiology of an uncultivated lineage of Aigarchaeota from an oxic, hot spring filamentous "streamer" community.',
      authors: ['Beam JP', 'Jay ZJ', 'Schmid MC', 'Rusch DB', 'Romine MF', 'Jennings Rde M', 'Kozubal MA', 'Tringe SG', 'Wagner M', 'Inskeep WP'],
      journal: 'ISME J. 2016 Jan',
      issue: '10(1)',
      pages: '210-24',
      doi: '10.1038/ismej.2015.83',
    },
    {
      title: 'Tracking heavy water (D2O) incorporation for identifying and sorting active microbial cells.',
      authors: ['Berry D', 'Mader E', 'Lee TK', 'Woebken D', 'Wang Y', 'Zhu D', 'Palatinszky M', 'Schintlmeister A', 'Schmid MC', 'Hanson BT', 'Shterzer N', 'Mizrahi I', 'Rauch I', 'Decker T', 'Bocklitz T', 'Popp J', 'Gibson CM', 'Fowler PW', 'Huang WE', 'Wagner M'],
      journal: 'Proc Natl Acad Sci U S A. 2015 Jan 13',
      issue: '112(2)',
      pages: 'E194-203',
      doi: '10.1073/pnas.1420406112',
    },
    {
      title: 'Biology of a widespread uncultivated archaeon that contributes to carbon fixation in the subsurface.',
      authors: ['Probst AJ', 'Weinmaier T', 'Raymann K', 'Perras A', 'Emerson JB', 'Rattei T', 'Wanner G', 'Klingl A', 'Berg IA', 'Yoshinaga M', 'Viehweger B', 'Hinrichs KU', 'Thomas BC', 'Meck S', 'Auerbach AK', 'Heise M', 'Schintlmeister A', 'Schmid M', 'Wagner M', 'Gribaldo S', 'Banfield JF', 'Moissl-Eichinger C'],
      journal: 'Nat Commun. 2014 Nov 26',
      issue: '5',
      pages: '5497',
      doi: '10.1038/ncomms6497',
    },
    {
      title: 'Revisiting N₂ fixation in Guerrero Negro intertidal microbial mats with a functional single-cell approach.',
      authors: ['Woebken D', 'Burow LC', 'Behnam F', 'Mayali X', 'Schintlmeister A', 'Fleming ED', 'Prufert-Bebout L', 'Singer SW', 'Cortés AL', 'Hoehler TM', 'Pett-Ridge J', 'Spormann AM', 'Wagner M', 'Weber PK', 'Bebout BM'],
      journal: 'ISME J. 2015 Feb',
      issue: '9(2)',
      pages: '485-96',
      doi: '10.1038/ismej.2014.144',
    },
    {
      title: 'Nitrotoga-like bacteria are previously unrecognized key nitrite oxidizers in full-scale wastewater treatment plants.',
      authors: ['Lücker S', 'Schwarz J', 'Gruber-Dorninger C', 'Spieck E', 'Wagner M', 'Daims H'],
      journal: 'ISME J. 2015 Mar',
      issue: '9(3)',
      pages: '708-20',
      doi: '10.1038/ismej.2014.158',
    },
    {
      title: 'Growth of nitrite-oxidizing bacteria by aerobic hydrogen oxidation.',
      authors: ['Koch H', 'Galushko A', 'Albertsen M', 'Schintlmeister A', 'Gruber-Dorninger C', 'Lücker S', 'Pelletier E', 'Le Paslier D', 'Spieck E', 'Richter A', 'Nielsen PH', 'Wagner M', 'Daims H'],
      journal: 'Science. 2014 Aug 29',
      issue: '345(6200)',
      pages: '1052-4',
      doi: '10.1126/science.1256985',
    },
    {
      title: 'Functionally relevant diversity of closely related Nitrospira in activated sludge.',
      authors: ['Gruber-Dorninger C', 'Pester M', 'Kitzinger K', 'Savio DF', 'Loy A', 'Rattei T', 'Wagner M', 'Daims H'],
      journal: 'ISME J. 2015 Mar',
      issue: '9(3)',
      pages: '643-55',
      doi: '10.1038/ismej.2014.156',
    },
    {
      title: 'Genomic encyclopedia of bacteria and archaea: sequencing a myriad of type strains.',
      authors: ['Kyrpides NC', 'Hugenholtz P', 'Eisen JA', 'Woyke T', 'Göker M', 'Parker CT', 'Amann R', 'Beck BJ', 'Chain PS', 'Chun J', 'Colwell RR', 'Danchin A', 'Dawyndt P', 'Dedeurwaerdere T', 'DeLong EF', 'Detter JC', 'De Vos P', 'Donohue TJ', 'Dong XZ', 'Ehrlich DS', 'Fraser C', 'Gibbs R', 'et al'],
      journal: 'PLoS Biol. 2014 Aug 5',
      issue: '12(8)',
      pages: 'e1001920',
      doi: '10.1371/journal.pbio.1001920',
    },
    {
      title: 'A nanoscale secondary ion mass spectrometry study of dinoflagellate functional diversity in reef-building corals.',
      authors: ['Pernice M', 'Dunn SR', 'Tonk L', 'Dove S', 'Domart-Coulon I', 'Hoppe P', 'Schintlmeister A', 'Wagner M', 'Meibom A'],
      journal: 'Environ Microbiol. 2015 Oct',
      issue: '17(10)',
      pages: '3570-80',
      doi: '10.1111/1462-2920.12518',
    },
    {
      title: 'Longitudinal study of murine microbiota activity and interactions with the host during acute inflammation and recovery.',
      authors: ['Schwab C', 'Berry D', 'Rauch I', 'Rennisch I', 'Ramesmayer J', 'Hainzl E', 'Heider S', 'Decker T', 'Kenner L', 'Müller M', 'Strobl B', 'Wagner M', 'Schleper C', 'Loy A', 'Urich T'],
      journal: 'ISME J. 2014 May',
      issue: '8(5)',
      pages: '1101-14',
      doi: '10.1038/ismej.2013.223',
    },
    {
      title: 'NxrB encoding the beta subunit of nitrite oxidoreductase as functional and phylogenetic marker for nitrite-oxidizing Nitrospira.',
      authors: ['Pester M', 'Maixner F', 'Berry D', 'Rattei T', 'Koch H', 'Lücker S', 'Nowka B', 'Richter A', 'Spieck E', 'Lebedeva E', 'Loy A', 'Wagner M', 'Daims H'],
      journal: 'Environ Microbiol. 2014 Oct',
      issue: '16(10)',
      pages: '3055-71',
      doi: '10.1111/1462-2920.12300',
    },
    {
      title: 'High-fat diet alters gut microbiota physiology in mice.',
      authors: ['Daniel H', 'Gholami AM', 'Berry D', 'Desmarchelier C', 'Hahne H', 'Loh G', 'Mondot S', 'Lepage P', 'Rothballer M', 'Walker A', 'Böhm C', 'Wenning M', 'Wagner M', 'Blaut M', 'Schmitt-Kopplin P', 'Kuster B', 'Haller D', 'Clavel T'],
      journal: 'ISME J. 2014 Feb',
      issue: '8(2)',
      pages: '295-308',
      doi: '10.1038/ismej.2013.155',
    },
    {
      title: 'Host-compound foraging by intestinal microbiota revealed by single-cell stable isotope probing.',
      authors: ['Berry D', 'Stecher B', 'Schintlmeister A', 'Reichert J', 'Brugiroux S', 'Wild B', 'Wanek W', 'Richter A', 'Rauch I', 'Decker T', 'Loy A', 'Wagner M'],
      journal: 'Proc Natl Acad Sci U S A. 2013 Mar 19',
      issue: '110(12)',
      pages: '4720-5',
      doi: '10.1073/pnas.1219247110',
    },
    {
      title: 'Interactions of nitrifying bacteria and heterotrophs: identification of a Micavibrio-like putative predator of Nitrospira spp.',
      authors: ['Dolinšek J', 'Lagkouvardos I', 'Wanek W', 'Wagner M', 'Daims H'],
      journal: 'Appl Environ Microbiol. 2013 Mar',
      issue: '79(6)',
      pages: '2027-37',
      doi: '10.1128/AEM.03408-12',
    },
    {
      title: 'Depletion of unwanted nucleic acid templates by selective cleavage: LNAzymes, catalytically active oligonucleotides containing locked nucleic acids, open a new window for detecting rare microbial community members.',
      authors: ['Dolinsek J', 'Dorninger C', 'Lagkouvardos I', 'Wagner M', 'Daims H'],
      journal: 'Appl Environ Microbiol. 2013 Mar',
      issue: '79(5)',
      pages: '1534-44',
      doi: '10.1128/AEM.03392-12',
    },
    {
      title: 'Complete genome sequences of Desulfosporosinus orientis DSM765T, Desulfosporosinus youngiae DSM17734T, Desulfosporosinus meridiei DSM13257T, and Desulfosporosinus acidiphilus DSM22704T.',
      authors: ['Pester M', 'Brambilla E', 'Alazard D', 'Rattei T', 'Weinmaier T', 'Han J', 'Lucas S', 'Lapidus A', 'Cheng JF', 'Goodwin L', 'Pitluck S', 'Peters L', 'Ovchinnikova G', 'Teshima H', 'Detter JC', 'Han CS', 'Tapia R', 'Land ML', 'Hauser L', 'Kyrpides NC', 'Ivanova NN', 'Pagani I', 'et al'],
      journal: 'J Bacteriol. 2012 Nov',
      issue: '194(22)',
      pages: '6300-1',
      doi: '10.1128/JB.01392-12',
    },
    {
      title: 'A straightforward DOPE (double labeling of oligonucleotide probes)-FISH (fluorescence in situ hybridization) method for simultaneous multicolor detection of six microbial populations.',
      authors: ['Behnam F', 'Vilcinskas A', 'Wagner M', 'Stoecker K'],
      journal: 'Appl Environ Microbiol. 2012 Aug',
      issue: '78(15)',
      pages: '5138-42',
      doi: '10.1128/AEM.00977-12',
    },
    {
      title: 'Phylotype-level 16S rRNA analysis reveals new bacterial indicators of health state in acute murine colitis.',
      authors: ['Berry D', 'Schwab C', 'Milinovich G', 'Reichert J', 'Ben Mahfoudh K', 'Decker T', 'Engel M', 'Hai B', 'Hainzl E', 'Heider S', 'Kenner L', 'Müller M', 'Rauch I', 'Strobl B', 'Wagner M', 'Schleper C', 'Urich T', 'Loy A'],
      journal: 'ISME J. 2012 Nov',
      issue: '6(11)',
      pages: '2091-106',
      doi: '10.1038/ismej.2012.39',
    },
    {
      title: 'Sulfate-reducing microorganisms in wetlands - fameless actors in carbon cycling and climate change.',
      authors: ['Pester M', 'Knorr KH', 'Friedrich MW', 'Wagner M', 'Loy A'],
      journal: 'Front Microbiol. 2012 Feb 28',
      issue: '3',
      pages: '72',
      doi: '10.3389/fmicb.2012.00072',
    },
    {
      title: 'amoA-based consensus phylogeny of ammonia-oxidizing archaea and deep sequencing of amoA genes from soils of four different geographic regions.',
      authors: ['Pester M', 'Rattei T', 'Flechl S', 'Gröngröft A', 'Richter A', 'Overmann J', 'Reinhold-Hurek B', 'Loy A', 'Wagner M'],
      journal: 'Environ Microbiol. 2012 Feb',
      issue: '14(2)',
      pages: '525-39',
      doi: '10.1111/j.1462-2920.2011.02666.x',
    },
    {
      title: 'New trends in fluorescence in situ hybridization for identification and functional analyses of microbes.',
      authors: ['Wagner M', 'Haider S'],
      journal: 'Curr Opin Biotechnol. 2012 Feb',
      issue: '23(1)',
      pages: '96-102',
      doi: '10.1016/j.copbio.2011.10.010',
    },
    {
      title: 'Thaumarchaeotes abundant in refinery nitrifying sludges express amoA but are not obligate autotrophic ammonia oxidizers.',
      authors: ['Mussmann M', 'Brito I', 'Pitcher A', 'Sinninghe Damsté JS', 'Hatzenpichler R', 'Richter A', 'Nielsen JL', 'Nielsen PH', 'Müller A', 'Daims H', 'Wagner M', 'Head IM'],
      journal: 'Proc Natl Acad Sci U S A. 2011 Oct 4',
      issue: '108(40)',
      pages: '16771-6',
      doi: '10.1073/pnas.1106427108',
    },
    {
      title: 'Barcoded primers used in multiplex amplicon pyrosequencing bias amplification.',
      authors: ['Berry D', 'Ben Mahfoudh K', 'Wagner M', 'Loy A'],
      journal: 'Appl Environ Microbiol. 2011 Nov',
      issue: '77(21)',
      pages: '7846-9',
      doi: '10.1128/AEM.05220-11',
    },
    {
      title: 'Systematic spatial bias in DNA microarray hybridization is caused by probe spot position-dependent variability in lateral diffusion.',
      authors: ['Steger D', 'Berry D', 'Haider S', 'Horn M', 'Wagner M', 'Stocker R', 'Loy A'],
      journal: 'PLoS One. 2011',
      issue: '6(8)',
      pages: 'e23727',
      doi: '10.1371/journal.pone.0023727',
    },
    {
      title: 'Bacteriocyte-associated gammaproteobacterial symbionts of the Adelges nordmannianae/piceae complex (Hemiptera: Adelgidae).',
      authors: ['Toenshoff ER', 'Penz T', 'Narzt T', 'Collingro A', 'Schmitz-Esser S', 'Pfeiffer S', 'Klepal W', 'Wagner M', 'Weinmaier T', 'Rattei T', 'Horn M'],
      journal: 'ISME J. 2012 Feb',
      issue: '6(2)',
      pages: '384-96',
      doi: '10.1038/ismej.2011.102',
    },
    {
      title: 'The Thaumarchaeota: an emerging view of their phylogeny and ecophysiology.',
      authors: ['Pester M', 'Schleper C', 'Wagner M'],
      journal: 'Curr Opin Microbiol. 2011 Jun',
      issue: '14(3)',
      pages: '300-6',
      doi: '10.1016/j.mib.2011.04.007',
    },
    {
      title: 'In situ techniques and digital image analysis methods for quantifying spatial localization patterns of nitrifiers and other microorganisms in biofilm and flocs.',
      authors: ['Daims H', 'Wagner M'],
      journal: 'Methods Enzymol. 2011',
      issue: '496',
      pages: '185-215',
      doi: '10.1016/B978-0-12-386489-5.00008-7',
    },
    {
      title: 'Proteomic analysis reveals a virtually complete set of proteins for translation and energy generation in elementary bodies of the amoeba symbiont Protochlamydia amoebophila.',
      authors: ['Sixt BS', 'Heinz C', 'Pichler P', 'Heinz E', 'Montanaro J', 'Op den Camp HJ', 'Ammerer G', 'Mechtler K', 'Wagner M', 'Horn M'],
      journal: 'Proteomics. 2011 May',
      issue: '11(10)',
      pages: '1868-92',
      doi: '10.1002/pmic.201000510',
    },
    {
      title: 'Microorganisms with novel dissimilatory (bi)sulfite reductase genes are widespread and part of the core microbiota in low-sulfate peatlands.',
      authors: ['Steger D', 'Wentrup C', 'Braunegger C', 'Deevong P', 'Hofer M', 'Richter A', 'Baranyi C', 'Pester M', 'Wagner M', 'Loy A'],
      journal: 'Appl Environ Microbiol. 2011 Feb',
      issue: '77(4)',
      pages: '1231-42',
      doi: '10.1128/AEM.01352-10',
    },
    {
      title: 'Proteomic analysis of the outer membrane of Protochlamydia amoebophila elementary bodies.',
      authors: ['Heinz E', 'Pichler P', 'Heinz C', 'Op den Camp HJ', 'Toenshoff ER', 'Ammerer G', 'Mechtler K', 'Wagner M', 'Horn M'],
      journal: 'Proteomics. 2010 Dec',
      issue: '10(24)',
      pages: '4363-76',
      doi: '10.1002/pmic.201000302',
    },
    {
      title: 'Inclusion membrane proteins of Protochlamydia amoebophila UWE25 reveal a conserved mechanism for host cell interaction among the Chlamydiae.',
      authors: ['Heinz E', 'Rockey DD', 'Montanaro J', 'Aistleitner K', 'Wagner M', 'Horn M'],
      journal: 'J Bacteriol. 2010 Oct',
      issue: '192(19)',
      pages: '5093-102',
      doi: '10.1128/JB.00605-10',
    },
    {
      title: 'A Nitrospira metagenome illuminates the physiology and evolution of globally important nitrite-oxidizing bacteria.',
      authors: ['Lücker S', 'Wagner M', 'Maixner F', 'Pelletier E', 'Koch H', 'Vacherie B', 'Rattei T', 'Damsté JS', 'Spieck E', 'Le Paslier D', 'Daims H'],
      journal: 'Proc Natl Acad Sci U S A. 2010 Jul 27',
      issue: '107(30)',
      pages: '13479-84',
      doi: '10.1073/pnas.1003860107',
    },
    {
      title: 'Raman microspectroscopy reveals long-term extracellular activity of Chlamydiae.',
      authors: ['Haider S', 'Wagner M', 'Schmid MC', 'Sixt BS', 'Christian JG', 'Häcker G', 'Pichler P', 'Mechtler K', 'Müller A', 'Baranyi C', 'Toenshoff ER', 'Montanaro J', 'Horn M'],
      journal: 'Mol Microbiol. 2010 Aug',
      issue: '77(3)',
      pages: '687-700',
      doi: '10.1111/j.1365-2958.2010.07241.x',
    },
    {
      title: 'A "rare biosphere" microorganism contributes to sulfate reduction in a peatland.',
      authors: ['Pester M', 'Bittner N', 'Deevong P', 'Wagner M', 'Loy A'],
      journal: 'ISME J. 2010 Dec',
      issue: '4(12)',
      pages: '1591-602',
      doi: '10.1038/ismej.2010.75',
    },
    {
      title: 'Comprehensive in silico prediction and analysis of chlamydial outer membrane proteins reflects evolution and life style of the Chlamydiae.',
      authors: ['Heinz E', 'Tischler P', 'Rattei T', 'Myers G', 'Wagner M', 'Horn M'],
      journal: 'BMC Genomics. 2009 Dec 29',
      issue: '10',
      pages: '634',
      doi: '10.1186/1471-2164-10-634',
    },
    {
      title: 'The genome of the amoeba symbiont "Candidatus Amoebophilus asiaticus" reveals common mechanisms for host cell interaction among amoeba-associated bacteria.',
      authors: ['Schmitz-Esser S', 'Tischler P', 'Arnold R', 'Montanaro J', 'Wagner M', 'Rattei T', 'Horn M'],
      journal: 'J Bacteriol. 2010 Feb',
      issue: '192(4)',
      pages: '1045-57',
      doi: '10.1128/JB.01379-09',
    },
    {
      title: 'Double labeling of oligonucleotide probes for fluorescence in situ hybridization (DOPE-FISH) improves signal intensity and increases rRNA accessibility.',
      authors: ['Stoecker K', 'Dorninger C', 'Daims H', 'Wagner M'],
      journal: 'Appl Environ Microbiol. 2010 Feb',
      issue: '76(3)',
      pages: '922-6',
      doi: '10.1128/AEM.02456-09',
    },
    {
      title: 'Single-cell ecophysiology of microbes as revealed by Raman microspectroscopy or secondary ion mass spectrometry imaging.',
      authors: ['Wagner M'],
      journal: 'Annu Rev Microbiol. 2009',
      issue: '63',
      pages: '411-29',
      doi: '10.1146/annurev.micro.091208.073233',
    },
    {
      title: 'Reverse dissimilatory sulfite reductase as phylogenetic marker for a subgroup of sulfur-oxidizing prokaryotes.',
      authors: ['Loy A', 'Duller S', 'Baranyi C', 'Mussmann M', 'Ott J', 'Sharon I', 'Béjà O', 'Le Paslier D', 'Dahl C', 'Wagner M'],
      journal: 'Environ Microbiol. 2009 Feb',
      issue: '11(2)',
      pages: '289-99',
      doi: '10.1111/j.1462-2920.2008.01760.x',
    },
    {
      title: 'probeCheck--a central resource for evaluating oligonucleotide probe coverage and specificity.',
      authors: ['Loy A', 'Arnold R', 'Tischler P', 'Rattei T', 'Wagner M', 'Horn M'],
      journal: 'Environ Microbiol. 2008 Oct',
      issue: '10(10)',
      pages: '2894-8',
      doi: '10.1111/j.1462-2920.2008.01706.x',
    },
    {
      title: 'Diversity of bacterial endosymbionts of environmental acanthamoeba isolates.',
      authors: ['Schmitz-Esser S', 'Toenshoff ER', 'Haider S', 'Heinz E', 'Hoenninger VM', 'Wagner M', 'Horn M'],
      journal: 'Appl Environ Microbiol. 2008 Sep',
      issue: '74(18)',
      pages: '5822-31',
      doi: '10.1128/AEM.01093-08',
    },
    {
      title: 'Chlamydia-like bacteria in respiratory samples of community-acquired pneumonia patients.',
      authors: ['Haider S', 'Collingro A', 'Walochnik J', 'Wagner M', 'Horn M'],
      journal: 'FEMS Microbiol Lett. 2008 Apr',
      issue: '281(2)',
      pages: '198-202',
      doi: '10.1111/j.1574-6968.2008.01099.x',
    },
    {
      title: 'A moderately thermophilic ammonia-oxidizing crenarchaeote from a hot spring.',
      authors: ['Hatzenpichler R', 'Lebedeva EV', 'Spieck E', 'Stoecker K', 'Richter A', 'Daims H', 'Wagner M'],
      journal: 'Proc Natl Acad Sci U S A. 2008 Feb 12',
      issue: '105(6)',
      pages: '2134-9',
      doi: '10.1073/pnas.0708857105',
    },
    {
      title: 'Diversity and mode of transmission of ammonia-oxidizing archaea in marine sponges.',
      authors: ['Steger D', 'Ettinger-Epstein P', 'Whalan S', 'Hentschel U', 'de Nys R', 'Wagner M', 'Taylor MW'],
      journal: 'Environ Microbiol. 2008 Apr',
      issue: '10(4)',
      pages: '1087-94',
      doi: '10.1111/j.1462-2920.2007.01515.x',
    },
    {
      title: 'Raman-FISH: combining stable-isotope Raman spectroscopy and fluorescence in situ hybridization for the single cell analysis of identity and function.',
      authors: ['Huang WE', 'Stoecker K', 'Griffiths R', 'Newbold L', 'Daims H', 'Whiteley AS', 'Wagner M'],
      journal: 'Environ Microbiol. 2007 Aug',
      issue: '9(8):1878-89.',
    },
    {
      title: 'Sponge-associated microorganisms: evolution, ecology, and biotechnological potential.',
      authors: ['Taylor MW', 'Radax R', 'Steger D', 'Wagner M'],
      journal: 'Microbiol Mol Biol Rev. 2007 Jun',
      issue: '71(2)',
      pages: '295-347',
    },
    {
      title: 'An Acanthamoeba sp. containing two phylogenetically different bacterial endosymbionts.',
      authors: ['Heinz E', 'Kolarov I', 'Kästner C', 'Toenshoff ER', 'Wagner M', 'Horn M'],
      journal: 'Environ Microbiol. 2007 Jun',
      issue: '9(6):1604-9.',
    },
    {
      title: 'Improved 16S rRNA-targeted probe set for analysis of sulfate-reducing bacteria by fluorescence in situ hybridization.',
      authors: ['Lücker S', 'Steger D', 'Kjeldsen KU', 'MacGregor BJ', 'Wagner M', 'Loy A'],
      journal: 'J Microbiol Methods. 2007 Jun',
      issue: '69(3)',
      pages: '523-8',
    },
    {
      title: 'Unravelling microbial communities with DNA-microarrays: challenges and future directions.',
      authors: ['Wagner M', 'Smidt H', 'Loy A', 'Zhou J'],
      journal: 'Microb Ecol. 2007 Apr',
      issue: '53(3)',
      pages: '498-506',
    },
    {
      title: 'Quantification of uncultured microorganisms by fluorescence microscopy and digital image analysis.',
      authors: ['Daims H', 'Wagner M'],
      journal: 'Appl Microbiol Biotechnol. 2007 May',
      issue: '75(2)',
      pages: '237-48',
    },
    {
      title: 'probeBase--an online resource for rRNA-targeted oligonucleotide probes: new features 2007.',
      authors: ['Loy A', 'Maixner F', 'Wagner M', 'Horn M'],
      journal: 'Nucleic Acids Res. 2007 Jan',
      issue: '35(Database issue)',
      pages: 'D800-4',
    },
    {
      title: 'Wastewater treatment: a model system for microbial ecology.',
      authors: ['Daims H', 'Taylor MW', 'Wagner M'],
      journal: 'Trends Biotechnol. 2006 Nov',
      issue: '24(11)',
      pages: '483-9',
    },
    {
      title: 'The Planctomycetes, Verrucomicrobia, Chlamydiae and sister phyla comprise a superphylum with biotechnological and medical relevance.',
      authors: ['Wagner M', 'Horn M'],
      journal: 'Curr Opin Biotechnol. 2006 Jun',
      issue: '17(3)',
      pages: '241-9',
    },
    {
      title: 'A vista for microbial ecology and environmental biotechnology.',
      authors: ['Rittmann BE', 'Hausner M', 'Löffler F', 'Love NG', 'Muyzer G', 'Okabe S', 'Oerther DB', 'Peccia J', 'Raskin L', 'Wagner M'],
      journal: 'Environ Sci Technol. 2006 Feb 15',
      issue: '40(4)',
      pages: '1096-103',
    },
    {
      title: 'daime, a novel image analysis program for microbial ecology and biofilm research.',
      authors: ['Daims H', 'Lücker S', 'Wagner M'],
      journal: 'Environ Microbiol. 2006 Feb',
      issue: '8(2):200-13.',
    },
    {
      title: 'Linking microbial community structure with function: fluorescence in situ hybridization-microautoradiography and isotope arrays.',
      authors: ['Wagner M', 'Nielsen PH', 'Loy A', 'Nielsen JL', 'Daims H'],
      journal: 'Curr Opin Biotechnol. 2006 Feb',
      issue: '17(1)',
      pages: '83-91',
    },
    {
      title: 'Functional marker genes for identification of sulfate-reducing prokaryotes.',
      authors: ['Wagner M', 'Loy A', 'Klein M', 'Lee N', 'Ramsing NB', 'Stahl DA', 'Friedrich MW'],
      journal: 'Methods Enzymol. 2005',
      issue: '397:469-89.',
    },
    {
      title: '"Candidatus Protochlamydia amoebophila", an endosymbiont of Acanthamoeba spp.',
      authors: ['Collingro A', 'Toenshoff ER', 'Taylor MW', 'Fritsche TR', 'Wagner M', 'Horn M'],
      journal: 'Int J Syst Evol Microbiol. 2005 Sep',
      issue: '55(Pt 5):1863-6.',
    },
    {
      title: 'Crystal ball. The community level: physiology and interactions of prokaryotes in the wilderness.',
      authors: ['Wagner M'],
      journal: 'Environ Microbiol. 2005 Apr',
      issue: '7(4)',
      pages: '483-5',
    },
    {
      title: '16S rRNA gene-based oligonucleotide microarray for environmental monitoring of the betaproteobacterial order "Rhodocyclales"',
      authors: ['Loy A', 'Schulz C', 'Lücker S', 'Schöpfer-Wendels A', 'Stoecker K', 'Baranyi C', 'Lehner A', 'Wagner M'],
      journal: 'Appl Environ Microbiol. 2005 Mar',
      issue: '71(3):1373-86.',
    },
    {
      title: 'Recovery of an environmental Chlamydia strain from activated sludge by co-cultivation with Acanthamoeba sp.',
      authors: ['Collingro A', 'Poppert S', 'Heinz E', 'Schmitz-Esser S', 'Essig A', 'Schweikert M', 'Wagner M', 'Horn M'],
      journal: 'Microbiology. 2005 Jan',
      issue: '151(Pt 1):301-9.',
    },
    {
      title: 'Microarray and functional gene analyses of sulfate-reducing prokaryotes in low-sulfate, acidic fens reveal cooccurrence of recognized genera and novel lineages.',
      authors: ['Loy A', 'Küsel K', 'Lehner A', 'Drake HL', 'Wagner M'],
      journal: 'Appl Environ Microbiol. 2004 Dec',
      issue: '70(12):6998-7009.',
    },
    {
      title: 'Bacterial endosymbionts of free-living amoebae.',
      authors: ['Horn M', 'Wagner M'],
      journal: 'J Eukaryot Microbiol. 2004 Sep-Oct',
      issue: '51(5)',
      pages: '509-14',
    },
    {
      title: 'Illuminating the evolutionary history of chlamydiae.',
      authors: ['Horn M', 'Collingro A', 'Schmitz-Esser S', 'Beier CL', 'Purkhold U', 'Fartmann B', 'Brandt P', 'Nyakatura GJ', 'Droege M', 'Frishman D', 'Rattei T', 'Mewes HW', 'Wagner M'],
      journal: 'Science. 2004 Apr 30',
      issue: '304(5671)',
      pages: '728-30',
    },
    {
      title: 'Fluorescence in situ hybridisation for the identification and characterisation of prokaryotes.',
      authors: ['Wagner M', 'Horn M', 'Daims H'],
      journal: 'Curr Opin Microbiol. 2003 Jun',
      issue: '6(3)',
      pages: '302-9',
    },
    {
      title: 'Microbial community composition and function in wastewater treatment plants.',
      authors: ['Wagner M', 'Loy A', 'Nogueira R', 'Purkhold U', 'Lee N', 'Daims H'],
      journal: 'Antonie Van Leeuwenhoek. 2002 Aug',
      issue: '81(1-4)',
      pages: '665-80',
    },
    {
      title: 'Bacterial community composition and function in sewage treatment systems.',
      authors: ['Wagner M', 'Loy A'],
      journal: 'Curr Opin Biotechnol. 2002 Jun',
      issue: '13(3)',
      pages: '218-27',
    },
  ],
  GND_DATA: [
    {
      name: 'Holger Daims',
      born: '1970',
      publications: [
        'Population structure and functional analyses by in situ techniques of nitrifying bacteria in wastewater treatment plants',
      ],
    },
    {
      name: 'Holger Daims',
      born: '1970',
      publications: [
        'Impacts and Importance of Ammonia- and Nitrite Oxidation in the Marine Nitrogen Cycle',
        'NxrB encoding the beta subunit of nitrite oxidoreductase as functional and phylogenetic marker for nitrite-oxidizing Nitrospira',
      ],
    },
    {
      name: 'Matthias Horn',
      born: '1971',
      publications: [
        'Molecular ecology of free-living amoebae and their bacterial endosymbionts',
      ],
    },
    {
      name: 'Alexander Loy a',
      born: null,
      publications: [
        'Distribution and Activity of Anammox and Sulfide-Oxidizing Nitrate-Reducing Bacteria in Oxygen Minimum Zones',
        'Phylogenetic and environmental diversity of DsrAB-type dissimilatory (bi)sulfite reductases',
      ],
    },
    {
      name: 'Michael Wagner',
      born: '1965',
      publications: [
        'Die Anwendung von in situ Hybridisierungssonden zur Aufklärung mikrobieller Populationsstrukturen in der Abwasserreinigung',
      ],
    },
  ],
};
