import path from 'path';
import { defineConfig } from 'vite';
import babel from '@rollup/plugin-babel';
import vue from '@vitejs/plugin-vue2';

// Todo: implement eslint
// import eslint from 'vite-plugin-eslint';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    babel({
      exclude: 'node_modules/**',
      // https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
      // user 'runtime' for libraries for improved code deduplication
      babelHelpers: 'runtime',
    }),
    // eslint({ cache: false }),
  ],
  resolve: {
    extensions: ['*', '.js', '.vue', '.json'],
    alias: {
      '@': path.resolve(__dirname, './src'),
      '~': path.resolve(__dirname, ''),
    },
  },
  build: {
    cssCodeSplit: true,
    minify: true,
    sourcemap: true,
    lib: {
      entry: path.resolve(__dirname, 'src/components/index.js'),
      name: 'BaseUiComponents',
      formats: ['es', 'cjs'],
      fileName: format => `[name].${format}.js`,
      // Note: exports property in package.json will be generated by build:update-package-exports
    },
    rollupOptions: {
      external: [
        'vue',
        'vue2-datepicker',
        'lazysizes',
        'swiper',
      ],
      output: {
        assetFileNames: (assetInfo) => {
          if (assetInfo.name === 'style.css') return 'base-ui-components.css';
          return assetInfo.name;
        },
        exports: 'named',
        globals: {
          vue: 'Vue',
          'vue2-datepicker': 'Datepicker',
          lazysizes: 'lazysizes',
          swiper: 'Swiper',
        },
        preserveModules: true,
        preserveModulesRoot: 'lib',
      },
    },
  },
  css: {
    postcss: {},
  },
  server: {
    port: 8080,
  },
});
