// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import BaseAutocompleteInput from './components/BaseAutocompleteInput/BaseAutocompleteInput';
import BaseBox from './components/BaseBox/BaseBox';
import BaseBoxButton from './components/BaseBoxButton/BaseBoxButton';
import BaseButton from './components/BaseButton/BaseButton';
import BaseCheckmark from './components/BaseCheckmark/BaseCheckmark';
import BaseChip from './components/BaseChip/BaseChip';
import BaseChipsBelow from './components/BaseChipsBelow/BaseChipsBelow';
import BaseChipsInput from './components/BaseChipsInput/BaseChipsInput';
import BaseDateInput from './components/BaseDateInput/BaseDateInput';
import BaseDropBox from './components/BaseDropBox/BaseDropBox';
import BaseDropDown from './components/BaseDropDown/BaseDropDown';
import BaseHoverBox from './components/BaseHoverBox/BaseHoverBox';
import BaseImageBox from './components/BaseImageBox/BaseImageBox';
import BaseInput from './components/BaseInput/BaseInput';
import BaseLoader from './components/BaseLoader/BaseLoader';
import BaseMediaPreview from './components/BaseMediaPreview/BaseMediaPreview';
import BaseMenuEntry from './components/BaseMenuEntry/BaseMenuEntry';
import BaseMenuList from './components/BaseMenuList/BaseMenuList';
import BaseMultilineTextInput from './components/BaseMultilineTextInput/BaseMultilineTextInput';
import BasePagination from './components/BasePagination/BasePagination';
import BasePopUp from './components/BasePopUp/BasePopUp';
import BaseSearch from './components/BaseSearch/BaseSearch';
import BaseSwitchButton from './components/BaseSwitchButton/BaseSwitchButton';
import BaseToggle from './components/BaseToggle/BaseToggle';
import BaseToggleGroup from './components/BaseToggleGroup/BaseToggleGroup';
import BaseUploadBar from './components/BaseUploadBar/BaseUploadBar';
import 'normalize.css';
import './styles/lib.scss';

// Export components individually
export {
  BaseAutocompleteInput,
  BaseBox,
  BaseBoxButton,
  BaseButton,
  BaseCheckmark,
  BaseChip,
  BaseChipsBelow,
  BaseChipsInput,
  BaseDateInput,
  BaseDropBox,
  BaseDropDown,
  BaseHoverBox,
  BaseImageBox,
  BaseInput,
  BaseLoader,
  BaseMediaPreview,
  BaseMenuEntry,
  BaseMenuList,
  BaseMultilineTextInput,
  BasePagination,
  BasePopUp,
  BaseSearch,
  BaseSwitchButton,
  BaseToggle,
  BaseToggleGroup,
  BaseUploadBar,
};

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('BaseAutocompleteInput', BaseAutocompleteInput);
  Vue.component('BaseBox', BaseBox);
  Vue.component('BaseBoxButton', BaseBoxButton);
  Vue.component('BaseButton', BaseButton);
  Vue.component('BaseCheckmark', BaseCheckmark);
  Vue.component('BaseChip', BaseChip);
  Vue.component('BaseChipsBelow', BaseChipsBelow);
  Vue.component('BaseChipsInput', BaseChipsInput);
  Vue.component('BaseDateInput', BaseDateInput);
  Vue.component('BaseDropBox', BaseDropBox);
  Vue.component('BaseDropDown', BaseDropDown);
  Vue.component('BaseHoverBox', BaseHoverBox);
  Vue.component('BaseImageBox', BaseImageBox);
  Vue.component('BaseInput', BaseInput);
  Vue.component('BaseLoader', BaseLoader);
  Vue.component('BaseMediaPreview', BaseMediaPreview);
  Vue.component('BaseMenuEntry', BaseMenuEntry);
  Vue.component('BaseMenuList', BaseMenuList);
  Vue.component('BaseMultilineTextInput', BaseMultilineTextInput);
  Vue.component('BasePagination', BasePagination);
  Vue.component('BasePopUp', BasePopUp);
  Vue.component('BaseSearch', BaseSearch);
  Vue.component('BaseSwitchButton', BaseSwitchButton);
  Vue.component('BaseToggle', BaseToggle);
  Vue.component('BaseToggleGroup', BaseToggleGroup);
  Vue.component('BaseUploadBar', BaseUploadBar);
}

// Export the library as a plugin
export default { install };
